public void test${1:Name}() throws Exception ${2} {
  ${3}
}
